export const quotes = [
  "The things you are most afraid to create are the things most worth creating.",
  "Discipline is choosing between what you want now and what you want most.",
  "Every day is a chance to be better than yesterday.",
  "Your body can do almost anything. It's your mind you have to convince.",
  "Small daily improvements lead to staggering long-term results.",
  "The secret of getting ahead is getting started.",
  "What you do every day matters more than what you do once in a while.",
  "You don't rise to the level of your goals. You fall to the level of your systems.",
  "Clarity is the antidote to anxiety.",
  "Be the version of yourself that future you is proud of.",
  "The quality of your decisions determines the quality of your life.",
  "Motion creates emotion.",
  "Nothing will work unless you do.",
  "Rest when you're done. Not when you're tired.",
  "The best project you'll ever work on is you.",
  "Act as if what you do makes a difference. It does.",
  "Consistency is the hallmark of the unbeatable.",
  "Don't count the days. Make the days count.",
  "You are what you repeatedly do.",
  "Energy flows where intention goes.",
  "One step at a time is all it takes to get you there.",
  "Champions keep playing until they get it right.",
  "The mind is everything. What you think, you become.",
  "Either you run the day or the day runs you.",
  "Success is the sum of small efforts repeated day in and day out.",
  "What gets measured gets managed.",
  "The body achieves what the mind believes.",
  "Progress, not perfection.",
  "Your future is created by what you do today, not tomorrow.",
  "Every expert was once a beginner.",
  "Strive not to be a success, but rather to be of value.",
  "Create. Maintain. Repeat.",
  "The present moment is where life lives.",
  "Silence is where clarity is found.",
  "Be still, and know.",
  "Your habits are votes for the person you want to become.",
  "What is mine to do today?",
  "Slow is smooth. Smooth is fast.",
  "Win the morning, win the day.",
  "Earn your rest.",
  "The harder the struggle, the more glorious the triumph.",
  "Clarity precedes success.",
  "Show up even when it's hard. Especially when it's hard.",
  "The obstacle is the way.",
  "Do the thing, then you'll have the power.",
  "A year from now you'll wish you started today.",
  "Make it simple. Make it happen.",
  "Greatness is a lot of small things done well.",
  "Your routine is your ritual.",
  "Peaceful mind. Powerful action.",
  "Build the body. Quiet the mind. Open the heart.",
  "What you tolerate, you teach.",
  "Less noise. More signal.",
  "Honor your commitments to yourself.",
  "You are always becoming.",
  "Create before you consume.",
  "The only limit is the one you set yourself.",
  "Execute with precision. Reflect with honesty.",
  "Choose hard now or hard later.",
  "The cave you fear to enter holds the treasure you seek.",
  "Own your morning.",
]

export function getDailyQuote() {
  const d = new Date()
  const doy = Math.floor((d - new Date(d.getFullYear(), 0, 0)) / 86400000)
  return quotes[doy % quotes.length]
}
